# Simple workflow for deploying static content to GitHub Pages
name: Deploy static content to Pages

on:
  # Runs on pushes targeting the default branch
  push:
    branches: ["main"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
      runs-on: ubuntu-latest
      name: Build API doc
      steps:
        - name: Checkout
          uses: actions/checkout@v3
        - name: Setup GitHub Pages
          uses: actions/configure-pages@v2
        - name: redoc-cli
          uses: trybeapp/redocly-openapi-cli-github-action@v0.0.1
          with:
            args: 'bundle open-api.yml -o public/index.html'
        - name: Upload artifact
          uses: actions/upload-pages-artifact@v1
          with:
            # Upload public directory
            path: './public'
  publish:
    runs-on: ubuntu-latest
    name: Publish API doc
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    needs: build
    steps:
      - name: Deploy artifact to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1
